# Generated by Django 5.2.13 on 2026-04-24 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publisher",
            name="editor",
        ),
        migrations.AddField(
            model_name="publisher",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="editing_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="journalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="journalist_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
