# Generated by Django 5.2.13 on 2026-04-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_publisher_editor_publisher_editors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.publisher",
            ),
        ),
    ]
