# Generated by Django 5.2.13 on 2026-04-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_publisher_journalistsubscription_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='description',
        ),
    ]
