# Generated by Django 5.2.13 on 2026-05-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newsletters",
                to="news.publisher",
            ),
        ),
    ]
